### PR TITLE
add utf-8 to read js script

### PR DESCRIPTION
**Pull request by jabolina**
Fix issue #6

Adding the codecs lib and utf-8 encoding while reading the js script.

### CODE REVIEW

**Comment by alfred82santa** [comment]
I dont undestand why you need it. Python3 reads text files using utf8 charset by default.

**Comment by alfred82santa** [comment]
Sorry, it's false it is OS dependent: https://docs.python.org/3/library/functions.html#open

So, solution is use encoding='utf-8' as key argument. Not import codec package.

**Comment by jabolina** [comment]
Yes, you are right. The encoding in my OS was not defined, so, with the codec will work even in this scenery.

But a question not related to this, when I get a quoted message, is there a way to get the quoted message object?
Is [this parameter?](https://github.com/alfred82santa/whalesong/blob/master/whalesong/managers/message.py#L151)

**Comment by alfred82santa** [comment]
Please, open a new issue. Issues are a way to get info from projects. It could be useful for others.

**Pull request merged**
